apiVersion: v1
kind: Pod
metadata:
  name: dnstest2
spec:
  containers:
  - image: xtoph/dns
    name: dnstest2container
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do sleep 5; done;"]    
    resources:
      requests:
        memory: 500M
        cpu: .5
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: Default
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule